### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by ichung** [mit-plv/cross-crypto#2]
Some things to work on in the near future: 

- n-step protocols to work on:
   - build up towards TLS-like protocol:
     - [ ] "PGP" - regularly sign encryption keys; people check the
           signatures and send you messages
     - [ ] session keys (cf Hugo Krawczyk, SIGMA)
     - [ ] multiple clients
     - [ ] KEM/PKE/DH
     - [ ] auth/confidentiality/both
     - [ ] preshared keys (similar to ratcheting)
     - [ ] key derivation
   - [ ] ratcheting - each round, send a message and new encryption+mac keys
     * could even show ratcheting property
     * probably will have the most problems.  not even really
       handled well by computational models
   - [ ] "kerberos" - trusted 3rd party which shares sym. keys with
         everyone; repeatedly negotiates a shared key between 2 people
         who use the shared key
   - [ ] server which takes adv message, prepends with "adv said: ", signs;
         wts all messages begin with "adv said: "
     * more or less superseded by "PGP"
 - [ ] compositionality of independence:
       if e, e' are independent from context C, then
       e ≈ e' -> C[e] ≈ C[e']
 - [ ] prove no_nonce_reuse
   - [ ] x <> y -> whp $x != $y
